version: "3.7"
services:
  nginx_proxy:
    image: reiz/nginx_proxy:0.0.3
    container_name: nginx_proxy
    volumes:
      - ./nginx_allowlist.conf:/usr/local/nginx/conf/nginx.conf
    environment:
      - TZ=Etc/UTC
    restart: always
